### PR TITLE
Add SAML Assertion Caching

### PR DESCRIPTION
**Pull request by mide**
This PR adds SAML Caching support. This will allow for `aws-google-auth` to be called multiple times without the user being prompted for a password or any two-factor tokens. 

I've added a handful of tests, and I'm trying to think of how to add more.

### CODE REVIEW

**Comment by mide** [comment]
I'm just thinking here - But perhaps this is a sane default (on by default, and have something like `--no-cache` to turn off the cache)?

**Comment by tjbaker** [comment]
I prefer caching on by default, and use the flag to force a refresh.

**Comment by mide** [comment]
SAML caching is now on by default:
```
# Nothing specified, uses cached, not prompted.
% aws-google-auth 
Assuming arn:aws:iam::123456789876:role/MY-ROLE
Credentials Expiration: 2018-01-19 17:10:01-05:00
export AWS_ACCESS_KEY_ID='<< MY ACCESS KEY >>' AWS_SECRET_ACCESS_KEY='<< MY SECRET KEY >>' AWS_SESSION_TOKEN='<< MY TOKEN >>'

# --no-cache specified, didn't use cache, prompted. 
% aws-google-auth --no-cache
Google Password:
Touch the flashing U2F device to authenticate...
Assuming arn:aws:iam::123456789876:role/MY-ROLE
Credentials Expiration: 2018-01-19 17:10:14-05:00
export AWS_ACCESS_KEY_ID='<< MY ACCESS KEY >>' AWS_SECRET_ACCESS_KEY='<< MY SECRET KEY >>' AWS_SESSION_TOKEN='<< MY TOKEN >>'
```

**Comment by nonspecialist** [comment]
Yep, the caching worked for me -- but the SAML assertion I'm getting back from Google has:

```xml
<!-- ... ->
<saml2:SubjectConfirmationData ... NotOnOrAfter="...">
<!-- ... ->
<saml2:Conditions ... NotOnOrAfter="...">
```
which, according to my slightly high-level knowledge of the SAML2 spec, means:

* `SubjectConfirmationData` time data specifies the time window during which the assertion can be supplied to the SP (in this case, AWS)
* `Conditions` time data specifies the time window that the SP should treat the session as valid (in other words, the maximum issued duration of the STS credentials)

According to the spec, the `SubjectConfirmationData` has to be within the `Conditions` time window.

Unless I'm mistaken, this means that caching the assertions is only of limited use, since Google issues its response with both `SubjectConfirmationData` and `Conditions` with a 10-minute window (5 minutes prior to the authentication time and 5 minutes after, to account for clock skew).

This concurs with my testing -- the cached assertion was usable to get new credentials, but only until 5 minutes after my initial authentication.

Is there a way to tell Google to issue assertions with a longer time window? I haven't been able to find one yet ...

**Comment by mide** [comment]
@nonspecialist I don't believe it's a configuration option in the Google Apps suite; or at least I don't see it in my options. For what it's worth, I don't see any mention of configuring that in [this Google Apps documentation](https://support.google.com/a/answer/6194963?hl=en).

**Comment by mide** [comment]
Any chance of this getting merged in this week? Many members of my team (and likely others) want this feature to land. 

Thanks!

**Comment by cliveza** [comment]
👍

**Comment by mide** [comment]
Woo! Thank you for the merge!

**Pull request merged**
