### PR TITLE
Add keyring support

### PR DESCRIPTION
**Pull request by dalen**
Add a `--keyring` option to fetch and store the password in the keyring.
Depends on the keyring module.

### CODE REVIEW

**Comment by stevemac007** [comment]
I've not see `keyring` before, does this use an operating system specific process for storing passwords? Like Keychain for OSX?

Is there any specific preconditions required for this module to work?

**Comment by stevemac007** [comment]
It looks like there are a couple of format issues that would be great to be fixed before merging.

```
./aws_google_auth/__init__.py:167:9: E112 expected an indented block
./aws_google_auth/__init__.py:167:14: E999 IndentationError: expected an indented block
```

**Comment by dalen** [comment]
Ooops, I had some auto formatting turned on and then tried to commit only lines I had actually changed. Must have done some mistake selecting changes there, will fix.

The keyring module supports a bunch of backends and has plugin support if you want to roll your own backend: https://pypi.python.org/pypi/keyring

> These recommended keyring backends are supported by the Python keyring lib:
> 
> * Mac OS X Keychain
> * Freedesktop Secret Service (requires secretstorage)
> * KWallet (requires dbus)
> * Windows Credential Locker

**Comment by dalen** [comment]
Great, thanks

**Comment by stevemac007** [comment]
Released as part of 0.0.24

**Pull request merged**
