### PR TITLE
U2F Support

### PR DESCRIPTION
**Pull request by toby-jn**
Add support for U2F (Yubikey) login. Some specifics of Google's U2F implementation requires some monkey patching.
Support optionally installed with `pip install -e aws-google-auth[u2f]`, to avoid requiring dependency on `python-u2flib-host`.

### CODE REVIEW

**Comment by tjbaker** [comment]
Is this PR abandoned or is there still hope?

**Comment by stevemac007** [comment]
There is always hope :D - It looks like Travis is unhappy with the Python3 usages of urllib.

If @toby-jn can look at fixing this I'll verify that the updates work for non U2F modes and approve the change.  I don't have a yubikey to confirm the update works as expected.

**Comment by stevemac007** [comment]
Probably also requires an update to the README to explain the conditional install route for those Yubikey users.

**Comment by mide** [comment]
I was able to get the test suites to pass for both Python 2 and Python3 with the following change to `__init__.py`:
```diff
diff --git a/aws_google_auth/__init__.py b/aws_google_auth/__init__.py
index a19bc93..ea408a6 100644
--- a/aws_google_auth/__init__.py
+++ b/aws_google_auth/__init__.py
@@ -9,11 +9,18 @@ import sys
 import requests
 import time
 import json
-import urlparse
 from bs4 import BeautifulSoup
 from lxml import etree
 import configparser

+# In Python3, the library 'urlparse' was renamed to 'urllib.parse'. For this to
+# maintain compatibility with both Python 2 and Python 3, the import must be
+# dynamically chosen based on the version detected.
+if sys.version_info >= (3, 0):
+    import urllib.parse
+else:
+    import urlparse
+
 from . import _version
 from . import prepare
```

```
$ python2 setup.py test
running test

... snip ...

Ran 3 tests in 0.159s

OK
```

```
$ python3 setup.py test
running test

... snip ...

Ran 3 tests in 0.184s

OK
```

This confirms @stevemac007's observation and shows that at leasts the tests work once that's happy. I can't speak on the functionality of the new U2F capabilities yet.

**Comment by mide** [comment]
Also, I'd wager that a [version bump](https://github.com/cevoaustralia/aws-google-auth/blob/master/aws_google_auth/_version.py) may be desirable as well.

**Comment by mide** [comment]
I addressed some of the feedback and test errors in #28.

**Comment by stevemac007** [comment]
U2F support delivered via #28 - Closing

**Pull request closed without merging**
