### PR TITLE
fix display of captcha url while neither xv or display utility are available

### PR DESCRIPTION
**Pull request by JeremJR**
see https://github.com/cevoaustralia/aws-google-auth/pull/91#issuecomment-413438202

https://pillow.readthedocs.io/en/5.2.x/handbook/tutorial.html

> The standard version of show() is not very efficient, since it saves the image to a temporary file and calls the xv utility to display the image. If you don’t have xv installed, it won’t even work. When it does work though, it is very handy for debugging and tests.

https://pillow.readthedocs.io/en/5.2.x/reference/Image.html#PIL.Image.Image.show

### CODE REVIEW

**Comment by tnguyen1** [comment]
I think you should rebase this change on aws-google-auth 0.0.27 or master.

**Comment by JeremJR** [comment]
@tnguyen1 I don't understand your point, https://github.com/JeremJR/aws-google-auth/tree/fix/display_captcha_url is 1 commit ahead of cevoaustralia:master.

**Comment by Colgaton** [comment]
Is this going to be pushed to master? I'm in windows 10 and I don't get the picture nor the url either.

**Comment by stevemac007** [comment]
Sorry for the radio silence, things have been busy recently - taking a look at the PR's raised over the past few weeks.

This looks good, but as per #112 we probably should always print the captcha URL in case the image fails.

**Comment by JeremJR** [comment]
Great, any idea about the date of the next release that will include https://github.com/cevoaustralia/aws-google-auth/pull/112 ?

**Comment by stevemac007** [comment]
I'm hoping to validate it all and push the next release in the next 24hrs, hopefully sooner if it all works as expected.

Just trying to validate the scenario on windows.

**Comment by stevemac007** [comment]
It seems that my Google account doesn't need a Captcha at the moment, so I'll do some testing of the image snippets across the operating systems I have access to.

**Comment by stevemac007** [comment]
Whitespace issues are mine, I'll merge and fix on master..  :ducks:

**Comment by JeremJR** [comment]
Thank you!

**Comment by stevemac007** [comment]
So this also seems to break OSX - I've excluded `darwin`

**Pull request merged**
