### PR TITLE
Find MFA options by action URL

### LINKED ISSUE #201: Cannot login: MFA stopped working, then took wrong choice
I signed in no problem on 2020-10-12, but today, 2020-10-13 I cannot sign in because MFA does not work. Looks like Google changed something. Note that `saml2aws` also [stopped working](https://github.com/Versent/saml2aws/issues/568).

Here are the requests (parameters omitted) the Debug log shows are being made:

```
GET /o/saml2/initsso
GET /ServiceLogin
POST /signin/v1/lookup 
GET /signin/challenge/pwd/1
POST /signin/challenge/pwd/1 
GET /signin/selectchallenge/2
```
At this point `aws-google-auth` gives me this prompt:
```
Choose MFA method from available:

Enter MFA choice number (9): 
```
Entering 9 (or anything else) gives me a `KeyError`.

Running the same command, sometimes I get other prompts. For example:
```
Choose MFA method from available:
4: OOTP (Google Prompt)
Enter MFA choice number (9): 4
MFA Type Chosen: OOTP (Google Prompt)
MFA token: 
```
Here I selected 4, but never received the Google Prompt on my phone.

After several attempts, getting only the above prompts, I finally got this prompt:
```
Choose MFA method from available:
3: SMS
4: OOTP (Google Prompt)
Enter MFA choice number (9): 4
MFA Type Chosen: OOTP (Google Prompt)
Enter SMS token: G-
```
Note that I chose OOTP, but then was prompted for (and received) an SMS token, and entering the SMS token authenticated me. Further API calls were:
```
POST /signin/challenge/ipp/4
GET /signin/challenge/ipp/4
# Here is where I entered my SMS token
POST /signin/challenge/ipp/4
GET /o/saml2/initsso
```
#### Update 1
Trying several more times, I did get to a prompt that was only SMS codes, and entering 3 (the displayed choice) yielded
```
MFA Type Chosen: SMS
Something went wrong - Could not find SAML response, check your credentials or use --save-failure-html to debug.
```
Selecting 4 when only SMS was shown as an option yielded a KeyError.

I added backup codes to my account hoping that would help. Interesting that it made the default MFA choice number when no options were provided increase from 9 to 10. After that, and a few more attempts, I got:
```
Please visit the following URL to view your CAPTCHA: https://accounts.google.com/Captcha?...
Captcha (case insensitive): unscuryar
Choose MFA method from available:
4: OOTP (Google Prompt)
Enter MFA choice number (10): 4
MFA Type Chosen: OOTP (Google Prompt)
ERROR:root:SAML lookup failed, storing failure page to 'saml.html' to assist with debugging.
Something went wrong - Could not find SAML response, check your credentials or use --save-failure-html to debug.
```
The saved saml.html showed that the page was asking for a backup code.

### LINKED ISSUE #202: No attempt to use U2F Security Key
I have a YubiKey U2F security key as my default MFA. `aws-google-auth` used to immediately use it when I logged in, but now it does not use it and instead prompts me to use a different MFA method. 

This appears to be caused by a change with Google's pages, but I do not fully understand how the U2F integration works. I can say when I look at the MFA challenge selector page given to `aws-google-auth` it says that the security key is "not supported on this device or browser".

### Update 1

On further investigation, it looks like U2F integration is switching to a JavaScript implementation. It may not be possible to support U2F without running JavaScript.

### PR DESCRIPTION
**Pull request by Nuru**
- Fixes #201 except for #202. Partial fix for #200 (now will not offer Google Prompt as an option if it uses the unsupported API).

- Scans the `selectchallenge` response page for form action URLs we know how to handle and offers those as a choice of MFA options. 

- Does not fix #202 failure to use YubiKey (Google now thinks the browser does not support a U2F key, so it is not offered as an option).
- Does not implement Google Prompt `dp` style, but restores proper function of Google Prompt `az` style.

- Backup codes remain unsupported (though they should be easy to implement). 

- Adds `--save-saml-flow` option to save all requests and responses prior to receiving the SAML assertion for troubleshooting.

### CODE REVIEW

**Comment by andreaso** [comment]
Currently looking into catching `/signin/challenge/skotp/` to cover the https://g.co/sc security key fallback.

Something which belongs in this PR/branch, or rather something we should try to get merged later separately?

**Comment by Nuru** [comment]
@stevemac007 can you review and approve this PR, or bring this to the attention of someone who can?

**Comment by forsberg** [comment]
@andreaso - if I understand you correctly, you're trying to fix #202, correct?

My five cents is that what we have here should be merged ASAP as it adds stability (I can now login using TOTP, on master it's quite erratic), while getting back the Yubikey/U2F functionality would be nice but can be handled in a separate PR.

**Comment by andreaso** [comment]
Hej Erik!

Well, at least I'm trying to work-around the https://github.com/cevoaustralia/aws-google-auth/issues/202 issue, with the https://g.co/sc one-time security codes being a viable option even when TOTP, etc is disabled for your G-Suite account.

I do have something crude working under https://github.com/andreaso/aws-google-auth/tree/wip/skotp-support, which is based on this PR.

But yeah, let's get this PR merged first, while I get some further testing/improvement on my patch internally.

**Comment by gageorsburn** [comment]
Is this going to go in?

**Comment by stevemac007** [comment]
Apols for the radio silence - 2020 was a crazy year for us all - I've got this ready to ship in the release shortly and will do work to triage the remaining outstanding issues and pr's over the coming days.

**Pull request merged**
