### PR TITLE
Prompt the user to insert their U2F Device

### PR DESCRIPTION
**Pull request by mide**
This replaces #36

### CODE REVIEW

**Comment by mide** [comment]
I know we've got a slight decrease in coverage, but can we consider merging this as-is?

**Comment by nonspecialist** [comment]
The message prompts the user to insert the U2F device and "press enter to try again" -- does the U2F library read the keypress? Because it isn't in the added code ...

**Comment by mide** [comment]
@nonspecialist the `input()` line is what captures the input, but that's in the `google.py`. Do you think a better place for this logic to live is the `u2f.py`? 
```
input("Insert your U2F device and press enter to try again...")
```

And @stevemac007 I agree 100% regarding the coverage. I'm finding a lot of this a bit tricky to write tests for (but I'm trying!)

**Comment by nonspecialist** [comment]
@mide oh 🤦‍♂️ of course it is. I claim my one pre-coffee brain fart for today.

I agree accepting the loss of coverage for this is ok.

**Pull request merged**
