### PR TITLE
Re-pick the role

### PR DESCRIPTION
**Pull request by pioneerit**
Hi, we had a daily flow when I use the same profile and switch it between roles/accounts.
Currently, I don't have an option to do it, that is why I compiled for us a custom version.

Not sure if you'd like to merge it as it is. If not, could you add an option to force the user to pick up a role again if I had the role from the previous run?
Thanks.

### CODE REVIEW

**Comment by stevemac007** [comment]
Looks good, might be cleaner to add `action='store_true'` to set the value of the argument automatically.

**Comment by stan1y** [comment]
It makes more sense (for me) to 
- either have config.role stored optionally 
- or be able to `aws-google-auth [-a|--assume role-name]` like

      $ aws-google-auth -a this-role
      $ aws-google-auth -a that-role

**Comment by stevemac007** [comment]
I do like the ability to specify the role in the command. If the role specified was not offered should the application fail or fallback to choosing a role?

Im on the fence between them both, if the latter you could use it as a way to get the original desired behaviour. `-a pickrole` or some other invalid role.

Not sure I like that sideffect of the flag though.

**Comment by nonspecialist** [comment]
I think if you're specifying options and that causes the application to get into a state where you're asking for something it can't give you, it should fail. By analogy, if you give it an incorrect password, or an invalid 2FA response, it should also fail -- rather than end up going around and around, re-prompting you each time.

**Comment by pioneerit** [comment]
Let me point that I want to have one small option - ignored store AWS arn role in the config and choose a new one.
I don't see the case when I'd like to pass the role name in CLI, specially if I need to it only once (or I can manually create with `google_config.role_arn` in `~/.aws/config`. Anyway, it is another discussion.

What do I need to do now (besides resolving new conflict) to make it as a part of the main repo?

`action=store_true` - it means that it will ask the role each time, it was not something I need, but if you say that this is a better approach - it will work for me too.
Anything else?

**Comment by stevemac007** [comment]
@pioneerit I agree specifying the role at the CLI is an alternate discussion, something I might look at in another request.

By my understanding `action='store_true'` will supply the value for the argument, not ask you every time. You have a default supplied, so will be that unless -a is specified. 

What it will do is allow you to use it as a standalone flag eg `aws-google-auth -a` vs `aws-google-auth -a true`

Without the 'store_true' this will happen.

```
$ aws-google-auth -a
usage: aws-google-auth [-h] [-u USERNAME] [-I IDP_ID] [-S SP_ID] [-R REGION]
                       [-d DURATION] [-p PROFILE] [-V] [-a ASK_ROLE]
aws-google-auth: error: argument -a/--ask-role: expected one argument
```
If you fix up the conflict and add the `store_true` this should be good to merge.

**Comment by pioneerit** [comment]
@stevemac007, thanks for the comments.
I updated the branch.

**Comment by nonspecialist** [comment]
LGTM :shipit:

**Pull request merged**
